Update docker-compose.yml

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -23,14 +23,13 @@ services:
       apk add --no-cache openssl ca-certificates &&
       corepack enable &&
       yarn install &&
-      if [ ! -f /app/api/db/schema.prisma ]; then
-        echo 'Prisma schema not found. Generating Prisma files.' &&
-        npx prisma init --schema=/app/api/db/schema.prisma --force; # Force init to avoid prompts
+      if [ -f /app/api/db/schema.prisma ]; then
+        npx prisma generate --schema=/app/api/db/schema.prisma --force; # Generate Prisma schema
       else
-        npx prisma generate --schema=/app/api/db/schema.prisma --force; # Force generate to avoid prompts
+        echo 'Prisma schema not found. Please ensure /app/api/db/schema.prisma exists.';
+        exit 1;
       fi &&
       if [ \"$NODE_ENV\" != \"production\" ]; then
-        yarn create redwood-app . --force --no-typescript --overwrite &&
         yarn rw dev;
       else
         yarn rw build &&
